# [doubleclick.net]
||ad.doubleclick.net^
||bid.g.doubleclick.net^
||click.googleadservices.com^
||googleads.g.doubleclick.net^
||pubads.g.doubleclick.net^
||pagead2.googlesyndication.com^
||stats.g.doubleclick.net^
||pixel.doubleclick.net^
||securepubads.g.doubleclick.net^
||adservice.google.com^
||pagead.l.doubleclick.net^
||www.googletagservices.com^
||cm.g.doubleclick.net^
||www.googleadservices.com^
||partner.googleadservices.com^
||ads.google.com^
||adwords.google.com^
||tpc.googlesyndication.com^
||static.doubleclick.net^
||m.doubleclick.net^
||ads.doubleclick.net^
||ad-emea.doubleclick.net^
||betamediavisor.doubleclick.net^
||cvpn.doubleclick.net^
||dfpapi.doubleclick.net^
||dsm.doubleclick.net^
||motifbeta.doubleclick.net^
||partnerad.l.doubleclick.net^
||advertisers.l.doubleclick.net^
||dart.l.doubleclick.net^
||dart-ad.l.doubleclick.net^
||dart-apac.l.doubleclick.net^
||mobile-displayads.l.doubleclick.net^
||pagead46.l.doubleclick.net^
||partnerad.l.doubleclick.net^
||rich-media-dynamic-ads-api.l.doubleclick.net^
||stats.l.doubleclick.net^

# [amazonaws.com]
||ads.amazonaws.com^
||ad-id-useast1.amazonaws.com^
||ad-id-uswest2.amazonaws.com^
||advertising.amazonaws.com^
||aax-us-east.amazon-adsystem.com^
||s3.amazonaws.com^
||aax.amazon-adsystem.com^
||adserve-uswest.amazon.com^
||amazon-adsystem.com^
||dynamodb.amazonaws.com^
||media.amazon-adsystem.com^
||aax.amazon.com^
||adtago.s3.amazonaws.com^
||analyticsengine.s3.amazonaws.com^
||analytics.s3.amazonaws.com^
||advice-ads.s3.amazonaws.com^
||aws.amazonaws.com^
||cloudfront.amazonaws.com^
||geo.amazonaws.com^
||ns-923.amazonaws.com^
||s3-3-w.amazonaws.com^
||s3-eu-west-3.amazonaws.com^
||s3-us-east-2.amazonaws.com^
||screenshare.amazonaws.com^
||u4.amazonaws.com^
||www.amazonaws.com^
||es.amazonaws.com^
||me-south-1.amazonaws.com^
||ns-947.amazonaws.com^
||r2.amazonaws.com^
||s3-ap-southeast-1.amazonaws.com^
||s3-deprecated-ap-southeast-2.amazonaws.com^
||tracker.amazonaws.com^
||u5.amazonaws.com^
||x1.amazonaws.com^
||ts.amazon-adsystem.com^
||m.media-amazon.com^

# [ads.youtube.com]
||googleads.g.doubleclick.net^
||pubads.g.doubleclick.net^
||ad.doubleclick.net^
||tpc.googlesyndication.com^
||pagead.l.doubleclick.net^
||video-stats.video.google.com^
||s.youtube.com^
||s0.2mdn.net^
||yt3.ggpht.com^
||ads.youtube.com^
||www.googleadservices.com^
||android.youtube.com^
||m.youtube.com^
||youtubei.googleapis.com^
||www.youtube-nocookie.com^
||manifest.googlevideo.com^
||r1---sn-*.googlevideo.com^
||rr1---sn-*.googlevideo.com^
||r1---sn-[a-z0-9]+\.googlevideo\.com^
||rr1---sn-[a-z0-9]+\.googlevideo\.com^
||r1---sn-*.gvt1.com^
||rr1---sn-*.gvt1.com^
||r1---sn-[a-z0-9]+\.gvt1\.com^
||rr1---sn-[a-z0-9]+\.gvt1\.com^
||redirector.googlevideo.com^
||stats.youtube.com^
||clients1.google.com^
||clients3.google.com^
||clients4.google.com^
||static.doubleclick.net^
||ads.google.com^
||pagead-googlehosted.l.googleusercontent.com^
